# Generated by Django 5.1 on 2024-09-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='list',
            new_name='todo_list',
        ),
    ]
