# Generated by Django 5.1 on 2024-09-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crud',
            new_name='user',
        ),
    ]
